bug fix:
  - "bug"
  - "Bug"
  - "BUG"
  - "fix"
  - "Fix"
  - "FIX"
  - "error"
  - "Error"
  - "ERROR"
  - "issue"
  - "Issue"
  - "ISSUE"
  - "problem"
  - "Problem"
  - "PROBLEM"

level 1:
  - "level[\\s_-]?1"
  - "Level[\\s_-]?1"
  - "LEVEL[\\s_-]?1"

level 2:
  - "level[\\s_-]?2"
  - "Level[\\s_-]?2"
  - "LEVEL[\\s_-]?2"

level 3:
  - "level[\\s_-]?3"
  - "Level[\\s_-]?3"
  - "LEVEL[\\s_-]?3"

gssoc25:
  - "gssoc25"
  - "GSSOC25"
  - "Gssoc25"

good first issue:
  - "good first issue"
  - "Good First Issue"
  - "GOOD FIRST ISSUE"

enhancement:
  - "enhancement"
  - "Enhancement"
  - "ENHANCEMENT"
  - "improvement"
  - "Improvement"
  - "IMPROVEMENT"

feature request:
  - "feature request"
  - "Feature Request"
  - "FEATURE REQUEST"
  - "suggestion"
  - "Suggestion"
  - "SUGGESTION"
  - "new feature"
  - "New Feature"
  - "NEW FEATURE"

documentation:
  - "documentation"
  - "Documentation"
  - "DOCUMENTATION"
  - "docs"
  - "Docs"
  - "DOCS"