bug:
    - "(bug|issue|error|problem|fail|failure|crash)"

feature:
    - "(feature|enhancement|improvement|new feature|new functionality)"

documentation:
    - "(documentation|docs|doc|readme)"

gssoc25:
    - "(gssoc25|gssoc 2025|gssoc 25)"

good first issue:
    - "(good first issue|good first bug|good first feature)"

enhancement:
    - "(enhancement|improvement|upgrade|update)"
