backend:
  - 'src/controllers/**'
  - 'src/models/**'
  - 'src/routes/**'
  - 'src/db/**'
  - 'src/utils/**'
  - 'src/middlewares/**'
  - 'init/**'
  - 'test/**'
  - '__tests__/**'

frontend:
  - 'src/views/**'
  - 'src/public/**'

documentation:
  - '**/*.md'

tests:
  - 'test/**'
  - '__tests__/**'
