name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature Request]: "
labels: [enhancement]
body:
    - type: checkboxes
      id: existing-issue
      attributes:
          label: 🔍 Is there an existing issue for this?
          description: Please search to confirm whether a similar feature has already been requested.
          options:
              - label: I have searched the existing issues
                required: true

    - type: textarea
      id: feature-description
      attributes:
          label: 📝 Feature Description
          description: Provide a clear and detailed description of the feature you’re requesting.
          placeholder: Describe the feature or enhancement you’d like to see.
      validations:
          required: true

    - type: textarea
      id: Expected-Improvements
      attributes:
          label: 💡 Expected Improvements
          description: Describe the expected improvements from this feature.
          placeholder: What improvements or enhancements do you expect this feature to bring?
      validations:
          required: true

    - type: textarea
      id: screenShots
      attributes:
          label: 📸 Add Screenshots (Optional)
          description: Attach images or sketches that illustrate the feature (if any).

    - type: dropdown
      id: priority
      attributes:
          label: 🚦 Priority Level
          description: How important is this feature to you?
          options:
              - High
              - Medium
              - Low
          default: 0
      validations:
          required: true

    - type: checkboxes
      id: terms
      attributes:
          label: ✅ Confirmation
          options:
              - label: "I have read the Contributing Guidelines"
                required: true
              - label: "I'm a GSSoC'24 contributor"
              - label: "I have starred the repository"
                required: true
