name: 💬 Auto Comment on Forked PR Opened

on:
    pull_request:
        types: [opened]
    pull_request_target:
        types: [opened]

permissions:
    pull-requests: write
    contents: read

jobs:
    comment-on-forked-pr:
        runs-on: ubuntu-latest
        steps:
            - name: 🔍 Check if PR is from a fork
              id: check
              run: |
                  if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
                    echo "is_fork=true" >> "$GITHUB_OUTPUT"
                  else
                    echo "is_fork=false" >> "$GITHUB_OUTPUT"
                  fi

            - name: 💬 Post welcome comment on forked PR
              if: steps.check.outputs.is_fork == 'true'
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const prNumber = context.payload.pull_request.number;
                      const prTitle = context.payload.pull_request.title;
                      const prAuthor = context.payload.pull_request.user.login;

                      const comment = `👋 Hi @${prAuthor}!

                      Thanks for opening this pull request from your fork titled **"${prTitle}"**.
                      We really appreciate your contribution — our team will review it shortly. 🙏

                      Happy contributing! 🚀`;

                      await github.rest.issues.createComment({
                        issue_number: prNumber,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: comment
                      });
