name: Label Issues and PRs

on:
    issues:
        types: [opened, edited, reopened]

    pull_request_target:
        types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
    issues: write
    pull-requests: write
    contents: read

jenv:
  DEFAULT_LABEL: gssoc25

jobs:
  label-issue:
    name: "Auto-label issues and PRs"
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.4
        with:
          configuration-path: .github/labeler.yml
          enable-versioned-regex: 0
          include-title: 1
          include-body: 1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/github-script@v7
        with:
          script: |
            const label = process.env.DEFAULT_LABEL;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            if (context.eventName === 'issues') {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: context.issue.number,
                labels: [label]
              });
            } else if (context.eventName === 'pull_request') {
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: context.payload.pull_request.number,
                labels: [label]
              });
            }